### ISSUE TITLE
一些三方插件的issue

### ISSUE THREAD

**Issue by DavidBlackCN** [LiteyukiStudio/LiteyukiBot#53]
# 问题反馈

## **请确保**

- 已认真阅读[文档]("https://bot.liteyuki.icu")，该问题不是文档提及的或你自己操作不当造成的
- 你的问题是在最新版本的代码上测试的
- 请勿重复提交相同或类似的issue

## **描述问题**

在使用部分第三方插件时，私聊bot可正常回应，在群聊中则无任何输出（部分插件异常部分正常，非风控）

## **如何复现**
举例插件：
使用最新版本bot & [nonebot-plugin-remake](https://github.com/noneplugin/nonebot-plugin-remake)
配置完毕后于私聊&群聊测试
### 预期
后台正常运行，bot正常回复信息

### 实际
私聊正常，群聊无任何输出

## **日志或截图**
私聊时正常输出Event will be handled by Matcher(type='message', module=nonebot_plugin_remake, lineno=38)
群聊无任何输出

## **设备信息**
- **系统**: [Windows 10 IoT LTSC]
- **Python**: [Python 3.10.11]

**补充内容**
以下插件测试后相同异常：
haruka_bot
SimpleMusic
nonebot_plugin_russian
nonebot-plugin-heweather

以下插件测试正常：
nonebot-plugin-setu-now
nonebot-plugin-today-in-history

不清楚以上问题是否和该bot框架相关（）

**Comment by DavidBlackCN** [comment]
补充：
[nonebot-plugin-handle](https://github.com/noneplugin/nonebot-plugin-handle)
[nonebot-plugin-wordle](https://github.com/noneplugin/nonebot-plugin-wordle)
均有相同问题

config(部分)：
```
command_start:
- '。'
host: 127.0.0.1
alconna_auto_completion: true
alconna_use_command_start: true
```

似乎所有附带指令前缀的插件都会有问题（？）

**Comment by snowykami** [comment]
大概看了一下，有点像这个问题，和alconna有关https://github.com/nonebot/plugin-alconna/issues/43

**Comment by DavidBlackCN** [comment]
补充x2
[nonebot_plugin_batarot](https://github.com/Perseus037/nonebot_plugin_batarot/tree/main/nonebot_plugin_batarot)可正常运行
难不成不同插件的handle写法会对alconna产生影响？

刚刚查看了上述issue，在此处问题为群聊内使用空后缀&带后缀，均无响应

**Comment by snowykami** [comment]
请问使用**nb-cli**创建的空Bot加载这些插件运行是否能复现这个BUG，这几天我稍微有点小忙，可能没太多时间测试

**Comment by DavidBlackCN** [comment]
刚才用空bot尝试了[nonebot-plugin-remake](https://github.com/noneplugin/nonebot-plugin-remake)，此bug可复现
当设置空后缀时在群聊内需要@bot并附上指令才有响应，同时后台ERROR
【@bot 人生重开】
```
07-21 11:54:14 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_remake, lineno=38) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot_plugin_remake\__init__.py", line 56, in _
    await remake.send(f"{msg}\n\n{des}")
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 237, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 190, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\debug\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo='3')
```


当继续下一条指令时则无任何输出
【随机】

**Comment by DavidBlackCN** [comment]
题外话：在执行 `。更新轻雪`时:

```
07-24 16:52:41 [⭕错误] <nonebot> Running AlconnaMatcher(type='', module=src.liteyuki_main.core, lineno=49) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\src\utils\base\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\src\liteyuki_main\core.py", line 61, in _
    success, logs = update_liteyuki()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by EillesWan** [comment]
> 补充： [nonebot-plugin-handle](https://github.com/noneplugin/nonebot-plugin-handle) [nonebot-plugin-wordle](https://github.com/noneplugin/nonebot-plugin-wordle) 均有相同问题
> 
> config(部分)：
> 
> ```
> command_start:
> - '。'
> host: 127.0.0.1
> alconna_auto_completion: true
> alconna_use_command_start: true
> ```
> 
> 似乎所有附带指令前缀的插件都会有问题（？）

wordle我这边可以运行的起来，handle确实有问题，你可以从我这边修改过的用：\
https://github.com/TriM-Organization/LiteyukiBot-TriM/tree/main/src/nonebot_plugins/trimo_plugin_handle

有可能是轻雪和插件冲突，等我有时间看看，暂时先自己修改一下吧。

**Comment by EillesWan** [comment]
> 题外话：在执行 `。更新轻雪`时:
> 
> ```
> 07-24 16:52:41 [⭕错误] <nonebot> Running AlconnaMatcher(type='', module=src.liteyuki_main.core, lineno=49) failed.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
>     return self._bootstrap(parent_sentinel)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
>     self.run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\src\utils\base\reloader.py", line 27, in _run
>     _nb_run(*args, **kwargs)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\__init__.py", line 335, in run
>     get_driver().run(*args, **kwargs)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
>     uvicorn.run(
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\uvicorn\main.py", line 577, in run
>     server.run()
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\uvicorn\server.py", line 65, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
>     self.run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
>     self._run_once()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
>     handle._run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
>     await _run_matcher(
> > File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
>     await handler(
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "C:\Users\Administrator\Desktop\QQbot\Nonebot\LiteyukiBot\src\liteyuki_main\core.py", line 61, in _
>     success, logs = update_liteyuki()
> TypeError: cannot unpack non-iterable NoneType object
> ```

有事尽量开新issue，另外，这个问题是正常发生的，重启一下就行。如果还这样的话，就手动git pull，希望解决
